package cachetoken

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// The token is a wire format shared by two implementations in two languages:
// this package mints it in the cache service's own tests and in any Go caller,
// and packages/backend/convex/cacheToken.ts mints it in the control plane that
// actually issues one to a job. "Signing-compatible" is not something either
// side can assert about itself, so both read this file.
//
// It is checked in rather than generated at test time on purpose. A vector
// regenerated by whichever implementation happens to run first proves only that
// that implementation agrees with itself; a vector in the repository is a third
// party both sides are measured against, and a diff on this file in a pull
// request is the review signal that the wire format moved.
//
// Regenerate with:
//
//	go test ./apps/cache-service/cachetoken -run TestSharedVectors -update
//
// and expect to justify the diff.
var update = flag.Bool("update", false, "rewrite testdata/vectors.json from the cases below")

const vectorsPath = "testdata/vectors.json"

// A 32-byte key, the shortest this package accepts, so the vectors also pin
// MinSigningKeyLen as a working length rather than only as a rejection.
const vectorKeyHex = "2f6a1d5c8b0e4739ac21fe5d90b3746182cd0af5e6931b7c48d250ea9f6c3b18"

type vectorFile struct {
	Comment       string         `json:"comment"`
	SigningKeyHex string         `json:"signingKeyHex"`
	Issue         []issueVector  `json:"issue"`
	Verify        []verifyVector `json:"verify"`
}

type issueVector struct {
	Name       string          `json:"name"`
	Why        string          `json:"why"`
	NowUnix    int64           `json:"nowUnix"`
	TTLSeconds int64           `json:"ttlSeconds"`
	Facts      vectorFacts     `json:"facts"`
	Token      string          `json:"token"`
	Claims     json.RawMessage `json:"claims"`
	CanWrite   bool            `json:"canWrite"`
	ReadScopes []string        `json:"readScopes"`
	WriteScope string          `json:"writeScope"`
}

// vectorFacts mirrors JobFacts with explicit JSON names, so the file reads the
// same from TypeScript as the struct does from Go.
type vectorFacts struct {
	Repository     string `json:"repository"`
	HeadRepository string `json:"headRepository"`
	Event          string `json:"event"`
	Ref            string `json:"ref"`
	BaseRef        string `json:"baseRef"`
	DefaultBranch  string `json:"defaultBranch"`
	Attempt        string `json:"attempt"`
}

func (f vectorFacts) facts() JobFacts {
	return JobFacts{
		Repository:     f.Repository,
		HeadRepository: f.HeadRepository,
		Event:          f.Event,
		Ref:            f.Ref,
		BaseRef:        f.BaseRef,
		DefaultBranch:  f.DefaultBranch,
		Attempt:        f.Attempt,
	}
}

type verifyVector struct {
	Name    string `json:"name"`
	Why     string `json:"why"`
	NowUnix int64  `json:"nowUnix"`
	Token   string `json:"token"`
	// Error is "", "malformed", "signature", "expired" or "no-repository".
	// Naming the failure rather than only asserting that one happened is what
	// keeps the two implementations agreeing on WHICH rule rejected a token.
	Error  string          `json:"error"`
	Claims json.RawMessage `json:"claims"`
}

// issuedAt is a fixed instant, chosen once so the vectors are reproducible:
// 2026-08-18T12:00:00Z, the same clock the server suite pins.
const issuedAt = 1787054400

// The case table. Every entry exists because it exercises a decision that could
// be implemented differently in the other language and still look right.
var issueCases = []issueVector{
	{
		Name:       "a push on the default branch writes to its own ref",
		Why:        "the ordinary case: trusted code, so write proves itself and the read order is own-ref then default branch",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "Fanzzzd/erainfra",
			Event:          "push",
			Ref:            "refs/heads/main",
			DefaultBranch:  "refs/heads/main",
			Attempt:        "rc-e2e-8f21c0a",
		},
	},
	{
		Name:       "a push with no head repository still writes",
		Why:        "most events carry no head repository at all; only a pull-request event treats absence as foreign",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:    "Fanzzzd/erainfra",
			Event:         "push",
			Ref:           "refs/heads/feature-x",
			DefaultBranch: "refs/heads/main",
		},
	},
	{
		Name:       "a same-repository pull request writes to the merge ref",
		Why:        "a branch pushed to this repository is code this repository controls, pull request or not",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "Fanzzzd/erainfra",
			Event:          "pull_request",
			Ref:            "refs/pull/7/merge",
			BaseRef:        "refs/heads/main",
			DefaultBranch:  "refs/heads/main",
		},
	},
	{
		Name:       "a fork pull request reads the base branch and writes nothing",
		Why:        "ADR 0007 rule 2, the poisoning attack: the ref collapses to the base and the base ref is cleared, so the job has no scope of its own",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "attacker/erainfra",
			Event:          "pull_request",
			Ref:            "refs/pull/9/merge",
			BaseRef:        "refs/heads/main",
			DefaultBranch:  "refs/heads/main",
		},
	},
	{
		Name:       "a pull request whose head repository is unknown is treated as a fork",
		Why:        "absence is never a successful measurement; on a pull request an unnamed head is the fact that decides this going unmeasured",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:    "Fanzzzd/erainfra",
			Event:         "pull_request",
			Ref:           "refs/pull/9/merge",
			BaseRef:       "refs/heads/release",
			DefaultBranch: "refs/heads/main",
		},
	},
	{
		Name:       "issue_comment on a fork's pull request does not write",
		Why:        "the fork test is a foreign head repository on ANY event; issue_comment and workflow_run carry fork code into the base repository and neither is a pull-request event",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "attacker/erainfra",
			Event:          "issue_comment",
			Ref:            "refs/heads/main",
			DefaultBranch:  "refs/heads/main",
		},
	},
	{
		Name:       "an untrusted job with no base and no default branch can read nothing",
		Why:        "the collapse leaves an empty ref rather than the job's own, so the fallback is no scope at all instead of its own",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "attacker/erainfra",
			Event:          "pull_request",
			Ref:            "refs/pull/9/merge",
		},
	},
	{
		Name:       "an unnamed event never reaches read-write",
		Why:        "write is the case that has to prove itself, and an empty event proves nothing",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:    "Fanzzzd/erainfra",
			Ref:           "refs/heads/main",
			DefaultBranch: "refs/heads/main",
		},
	},
	{
		Name:       "a ref carrying HTML metacharacters",
		Why:        "Go's encoding/json escapes <, > and & by default and JSON.stringify does not, so a payload containing them is where two implementations silently stop producing the same bytes",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "Fanzzzd/erainfra",
			Event:          "push",
			Ref:            "refs/heads/a&b<c>d",
			DefaultBranch:  "refs/heads/main",
		},
	},
	{
		Name:       "a ref outside ASCII",
		Why:        "the payload is base64url over UTF-8 bytes, so a multi-byte ref pins the encoding rather than the character count",
		NowUnix:    issuedAt,
		TTLSeconds: 900,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "Fanzzzd/erainfra",
			Event:          "push",
			Ref:            "refs/heads/café-naïve-日本",
			DefaultBranch:  "refs/heads/main",
		},
	},
	{
		Name:       "the read order deduplicates and drops empties",
		Why:        "own ref, then base, then default branch, and a base that equals the default branch is one scope rather than two",
		NowUnix:    issuedAt,
		TTLSeconds: 60,
		Facts: vectorFacts{
			Repository:     "Fanzzzd/erainfra",
			HeadRepository: "Fanzzzd/erainfra",
			Event:          "pull_request",
			Ref:            "refs/pull/11/merge",
			BaseRef:        "refs/heads/main",
			DefaultBranch:  "refs/heads/main",
			Attempt:        "rc-e2e-0c19bd4",
		},
	},
}

func TestSharedVectors(t *testing.T) {
	key, err := hex.DecodeString(vectorKeyHex)
	if err != nil {
		t.Fatalf("decode vector key: %v", err)
	}

	if *update {
		writeVectors(t, key)
	}

	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("read %s: %v", vectorsPath, err)
	}
	var file vectorFile
	if err := json.Unmarshal(raw, &file); err != nil {
		t.Fatalf("parse %s: %v", vectorsPath, err)
	}
	if file.SigningKeyHex != vectorKeyHex {
		t.Fatalf("the vector file was signed with a different key: %s", file.SigningKeyHex)
	}
	if len(file.Issue) != len(issueCases) {
		t.Fatalf("the vector file holds %d issue cases, the table holds %d; regenerate with -update",
			len(file.Issue), len(issueCases))
	}

	for _, want := range file.Issue {
		t.Run("issue/"+want.Name, func(t *testing.T) {
			issuer, err := NewIssuer(key, time.Duration(want.TTLSeconds)*time.Second)
			if err != nil {
				t.Fatalf("new issuer: %v", err)
			}
			issuer.Now = func() time.Time { return time.Unix(want.NowUnix, 0).UTC() }

			token, claims, err := issuer.Issue(want.Facts.facts())
			if err != nil {
				t.Fatalf("issue: %v", err)
			}
			if token != want.Token {
				t.Errorf("token\n got %s\nwant %s", token, want.Token)
			}
			assertClaims(t, claims, want.Claims)
			if claims.CanWrite() != want.CanWrite {
				t.Errorf("CanWrite = %v, want %v", claims.CanWrite(), want.CanWrite)
			}
			if got := claims.ReadScopes(); !equalStrings(got, want.ReadScopes) {
				t.Errorf("ReadScopes = %q, want %q", got, want.ReadScopes)
			}
			if claims.WriteScope() != want.WriteScope {
				t.Errorf("WriteScope = %q, want %q", claims.WriteScope(), want.WriteScope)
			}
		})
	}

	verifier, err := NewVerifier(key)
	if err != nil {
		t.Fatalf("new verifier: %v", err)
	}
	for _, want := range file.Verify {
		t.Run("verify/"+want.Name, func(t *testing.T) {
			claims, err := verifier.Verify(want.Token, time.Unix(want.NowUnix, 0).UTC())
			if name := errorName(err); name != want.Error {
				t.Fatalf("Verify failed with %q, want %q (%v)", name, want.Error, err)
			}
			if want.Error != "" {
				return
			}
			assertClaims(t, claims, want.Claims)
		})
	}
}

func errorName(err error) string {
	switch {
	case err == nil:
		return ""
	case errors.Is(err, ErrMalformed):
		return "malformed"
	case errors.Is(err, ErrSignature):
		return "signature"
	case errors.Is(err, ErrExpired):
		return "expired"
	case errors.Is(err, ErrNoRepository):
		return "no-repository"
	default:
		return "unknown"
	}
}

// assertClaims compares by KEY, not by key order: the file is written with
// json.MarshalIndent and read back through a map, so the field order the wire
// format depends on is pinned by the token itself rather than here. Comparing
// two sorted maps is what makes an extra or misspelled key in the file a
// failure instead of a silently absent field.
func assertClaims(t *testing.T, got Claims, want json.RawMessage) {
	t.Helper()
	if string(sortedJSON(t, mustMarshal(t, got))) != string(sortedJSON(t, want)) {
		t.Errorf("claims\n got %s\nwant %s",
			sortedJSON(t, mustMarshal(t, got)), sortedJSON(t, want))
	}
}

func mustMarshal(t *testing.T, value any) []byte {
	t.Helper()
	encoded, err := json.Marshal(value)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return encoded
}

func sortedJSON(t *testing.T, raw []byte) []byte {
	t.Helper()
	var fields map[string]any
	if err := json.Unmarshal(raw, &fields); err != nil {
		t.Fatalf("parse claims %s: %v", raw, err)
	}
	return mustMarshal(t, fields)
}

func equalStrings(got, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	for index := range got {
		if got[index] != want[index] {
			return false
		}
	}
	return true
}

func writeVectors(t *testing.T, key []byte) {
	t.Helper()
	file := vectorFile{
		Comment: "Shared cache-token vectors. Read by apps/cache-service/cachetoken " +
			"(Go) and packages/backend/tests/cacheToken.test.ts (TypeScript); " +
			"neither may regenerate it to make itself pass. See vectors_test.go.",
		SigningKeyHex: vectorKeyHex,
	}

	for _, testCase := range issueCases {
		issuer, err := NewIssuer(key, time.Duration(testCase.TTLSeconds)*time.Second)
		if err != nil {
			t.Fatalf("new issuer: %v", err)
		}
		issuer.Now = func() time.Time { return time.Unix(testCase.NowUnix, 0).UTC() }
		token, claims, err := issuer.Issue(testCase.Facts.facts())
		if err != nil {
			t.Fatalf("issue %q: %v", testCase.Name, err)
		}
		encoded, err := json.Marshal(claims)
		if err != nil {
			t.Fatalf("marshal claims: %v", err)
		}
		testCase.Token = token
		testCase.Claims = encoded
		testCase.CanWrite = claims.CanWrite()
		testCase.ReadScopes = claims.ReadScopes()
		testCase.WriteScope = claims.WriteScope()
		file.Issue = append(file.Issue, testCase)
	}

	// The verify half. The first case reuses a minted token; the rest are
	// hand-built, because a rejection cannot be produced by an issuer that
	// refuses to produce it.
	valid := file.Issue[0]
	// A byte in the MIDDLE of the MAC segment. The LAST base64 character of a
	// 32-byte MAC carries four meaningful bits and two of padding, so editing
	// it can produce a different string that decodes to the same bytes -- which
	// verifies, and would make this case assert nothing.
	tampered := []byte(valid.Token)
	target := len(tampered) - 10
	if tampered[target] == 'A' {
		tampered[target] = 'B'
	} else {
		tampered[target] = 'A'
	}

	noRepository, err := sign(key, Claims{
		Ref:        "refs/heads/main",
		Permission: PermissionReadWrite,
		IssuedAt:   issuedAt,
		ExpiresAt:  issuedAt + 900,
	})
	if err != nil {
		t.Fatalf("sign a claim set with no repository: %v", err)
	}
	unknownPermission, err := sign(key, Claims{
		Repository: "Fanzzzd/erainfra",
		Ref:        "refs/heads/main",
		Permission: "admin",
		IssuedAt:   issuedAt,
		ExpiresAt:  issuedAt + 900,
	})
	if err != nil {
		t.Fatalf("sign a claim set with an unknown permission: %v", err)
	}
	unknownPermissionClaims, err := json.Marshal(Claims{
		Repository: "Fanzzzd/erainfra",
		Ref:        "refs/heads/main",
		Permission: PermissionRead,
		IssuedAt:   issuedAt,
		ExpiresAt:  issuedAt + 900,
	})
	if err != nil {
		t.Fatalf("marshal the normalised claims: %v", err)
	}

	file.Verify = []verifyVector{
		{
			Name:    "a token inside its window verifies",
			Why:     "the positive case, read back at a moment other than the one it was minted at",
			NowUnix: issuedAt + 300,
			Token:   valid.Token,
			Claims:  valid.Claims,
		},
		{
			Name:    "leeway covers a small clock skew",
			Why:     "the verifier absorbs 30s of skew between issuer and service; one second past expiry is still inside it",
			NowUnix: issuedAt + 901,
			Token:   valid.Token,
			Claims:  valid.Claims,
		},
		{
			Name:    "past expiry plus leeway is expired",
			Why:     "the leeway is a bound, not an extension; a token handed to untrusted code stops working",
			NowUnix: issuedAt + 900 + 31,
			Token:   valid.Token,
			Error:   "expired",
		},
		{
			Name:    "a flipped signature byte does not verify",
			Why:     "the MAC covers prefix and payload, so any edit to either is a signature failure rather than a parse failure",
			NowUnix: issuedAt + 300,
			Token:   string(tampered),
			Error:   "signature",
		},
		{
			Name:    "two segments is malformed",
			Why:     "a shape that is not prefix.payload.mac is rejected before anything is decoded",
			NowUnix: issuedAt + 300,
			Token:   "erainfra-cache-v1.e30",
			Error:   "malformed",
		},
		{
			Name:    "another version prefix is malformed",
			Why:     "the prefix versions the wire format: a future layout is rejected here rather than misparsed",
			NowUnix: issuedAt + 300,
			Token:   "erainfra-cache-v2." + splitPayload(valid.Token) + ".AAAA",
			Error:   "malformed",
		},
		{
			Name:    "a token with no repository claim is refused",
			Why:     "ADR 0007 rule 1: a request whose token carries no repository claim is rejected rather than defaulted",
			NowUnix: issuedAt + 300,
			Token:   noRepository,
			Error:   "no-repository",
		},
		{
			Name:    "an unknown permission reads as read",
			Why:     "anything that is not exactly read-write is read, so a claim set that fails to decide cannot decide write by accident",
			NowUnix: issuedAt + 300,
			Token:   unknownPermission,
			Claims:  unknownPermissionClaims,
		},
	}

	encoded, err := json.MarshalIndent(file, "", "  ")
	if err != nil {
		t.Fatalf("marshal vectors: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(vectorsPath), 0o755); err != nil {
		t.Fatalf("create testdata: %v", err)
	}
	if err := os.WriteFile(vectorsPath, append(encoded, '\n'), 0o644); err != nil {
		t.Fatalf("write %s: %v", vectorsPath, err)
	}
	t.Logf("rewrote %s", vectorsPath)
}

func splitPayload(token string) string {
	first := -1
	for index := range len(token) {
		if token[index] == '.' {
			if first < 0 {
				first = index
				continue
			}
			return token[first+1 : index]
		}
	}
	return ""
}
