package netpolicy

import (
	"encoding/json"
	"fmt"
	"strings"
)

// CNIDataDir holds host-local's address reservations. It lives under the
// Runner Center state directory so a host that also runs Docker or Kubernetes
// CNI keeps its own allocations untouched.
const CNIDataDir = "/var/lib/runner-center/cni/networks"

const cniVersion = "1.0.0"

// Conflist renders the CNI configuration list for the policy. The output is
// deterministic, so an operator can diff what is installed against what this
// build expects, and Verify can compare the two exactly.
func (p Policy) Conflist() ([]byte, error) {
	if err := p.Validate(); err != nil {
		return nil, err
	}
	ptp := map[string]any{
		"type":   "ptp",
		"ipMasq": true,
		"ipam": map[string]any{
			"type":    "host-local",
			"subnet":  p.Subnet,
			"dataDir": CNIDataDir,
			"routes":  []any{map[string]any{"dst": "0.0.0.0/0"}},
		},
		"dns": map[string]any{"nameservers": toAnySlice(p.Nameservers)},
	}
	if p.MTU > 0 {
		ptp["mtu"] = p.MTU
	}
	document := map[string]any{
		"cniVersion": cniVersion,
		"name":       p.Name,
		"plugins": []any{
			ptp,
			// The firewall plugin admits return traffic for the guest's own
			// connections. It is not what denies anything: the nftables table is.
			map[string]any{"type": "firewall", "backend": "iptables"},
			// tc-redirect-tap must run last. It converts the veth the earlier
			// plugins configured into the tap device Firecracker attaches to.
			map[string]any{"type": "tc-redirect-tap"},
		},
	}
	rendered, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("render CNI configuration: %w", err)
	}
	return append(rendered, '\n'), nil
}

// Nftables renders the table that enforces the policy.
//
// The chains hook the kernel at a priority just ahead of the filter default so
// a drop lands before another table could accept, but they keep an accept
// policy: a drop policy in this table would break every unrelated flow on a
// host that also runs Docker. Isolation therefore comes from explicit drop
// verdicts scoped to the guest subnet, which are final wherever they match.
func (p Policy) Nftables() (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}
	var builder strings.Builder
	write := func(format string, args ...any) {
		fmt.Fprintf(&builder, format, args...)
	}
	write("#!/usr/sbin/nft -f\n")
	write("# Generated by Runner Center. Edit the Profile policy, not this file:\n")
	write("# runner-center-runtime preflight rejects a table that no longer matches.\n")
	write("table inet %s\n", TableName)
	write("delete table inet %s\n\n", TableName)
	write("table inet %s {\n", TableName)
	write("\tset %s {\n\t\ttype ipv4_addr\n\t\tflags interval\n\t\telements = { %s }\n\t}\n\n",
		GuestSetName, p.Subnet)
	write("\tset %s {\n\t\ttype ipv4_addr\n\t\tflags interval\n", AllowSetName)
	if allowed := p.allowedOrEmpty(); len(allowed) > 0 {
		write("\t\telements = { %s }\n", joinCIDRs(allowed))
	}
	write("\t}\n\n")

	write("\tchain forward {\n")
	write("\t\ttype filter hook forward priority filter - 10; policy accept;\n")
	write("\t\tip saddr @%s ip daddr @%s drop comment \"%s\"\n",
		GuestSetName, GuestSetName, RuleDenyEastWest)
	write("\t\tip saddr @%s ip daddr @%s accept comment \"%s\"\n",
		GuestSetName, AllowSetName, RuleAllowDestinations)
	write("\t\tip saddr @%s ip daddr { %s } drop comment \"%s\"\n",
		GuestSetName, joinCIDRs(deniedRanges), RuleDenyPrivate)
	if p.EgressMode == EgressAllowlist {
		write("\t\tip saddr @%s drop comment \"%s\"\n", GuestSetName, RuleDenyDefault)
	}
	write("\t}\n\n")

	// A guest needs no host service at all. MMDS is answered by the VMM before a
	// packet reaches the host stack, and IPAM is static, so nothing legitimate
	// is addressed to the host itself.
	write("\tchain input {\n")
	write("\t\ttype filter hook input priority filter - 10; policy accept;\n")
	write("\t\tip saddr @%s drop comment \"%s\"\n", GuestSetName, RuleDenyHostInput)
	write("\t}\n")
	write("}\n")
	return builder.String(), nil
}

// ExpectedRules is the exact, ordered list of rule comments each chain must
// contain. Verify compares it against the live table, so both a removed rule
// and an inserted one fail readiness.
func (p Policy) ExpectedRules() map[string][]string {
	forward := []string{RuleDenyEastWest, RuleAllowDestinations, RuleDenyPrivate}
	if p.EgressMode == EgressAllowlist {
		forward = append(forward, RuleDenyDefault)
	}
	return map[string][]string{
		"forward": forward,
		"input":   {RuleDenyHostInput},
	}
}

func toAnySlice(values []string) []any {
	result := make([]any, 0, len(values))
	for _, value := range values {
		result = append(result, value)
	}
	return result
}
