/**
 * Regenerates `convex/provisionerFirecrackerHost.generated.ts` from
 * `deploy/provision-firecracker-host.sh` and `deploy/systemd/runner-center-runtime.service`.
 *
 * Both have to travel inside the rendered install script: `/install --role worker-host` is one
 * curl with nothing else to fetch from this deployment, the provisioner refuses to install the
 * runtime service without its unit file beside it, and Convex bundles TypeScript, not repository
 * files, so the bytes are committed as a generated module rather than read at runtime. Base64,
 * because the provisioner is itself full of heredocs and quotes that no shell-quoting scheme
 * survives verbatim. A test asserts the module matches both files byte for byte, so editing either
 * without rerunning this fails CI instead of shipping stale bytes.
 *
 * Usage: pnpm --filter @erainfra/backend embed-firecracker-provisioner
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..", "..", "..");
const target = path.resolve(
  import.meta.dirname,
  "..",
  "convex",
  "provisionerFirecrackerHost.generated.ts",
);

// Newline-joined 76-column lines, because the install script carries these inside heredocs that
// `base64 -d` reads: wrapped lines diff readably and decode identically.
function constant(bytes: Buffer) {
  const lines = bytes.toString("base64").match(/.{1,76}/g) ?? [];
  return lines
    .map((line, index) => `  "${line}${index === lines.length - 1 ? "" : "\\n"}"`)
    .join(" +\n");
}

const provisioner = readFileSync(path.join(repoRoot, "deploy", "provision-firecracker-host.sh"));
const unit = readFileSync(
  path.join(repoRoot, "deploy", "systemd", "runner-center-runtime.service"),
);
const provisionerSha = createHash("sha256").update(provisioner).digest("hex");
const unitSha = createHash("sha256").update(unit).digest("hex");

writeFileSync(
  target,
  `// GENERATED by scripts/embed-firecracker-provisioner.ts — do not edit.
// Sources: deploy/provision-firecracker-host.sh (sha256 ${provisionerSha}),
//          deploy/systemd/runner-center-runtime.service (sha256 ${unitSha}).
// Regenerate with: pnpm --filter @erainfra/backend embed-firecracker-provisioner

/** \`deploy/provision-firecracker-host.sh\`, base64-encoded for interpolation into shell. */
export const FIRECRACKER_HOST_PROVISIONER_B64 =
${constant(provisioner)};

/** SHA-256 of the decoded provisioner, asserted by the sync test. */
export const FIRECRACKER_HOST_PROVISIONER_SHA256 =
  "${provisionerSha}";

/** \`deploy/systemd/runner-center-runtime.service\`, which the provisioner needs beside itself. */
export const FIRECRACKER_RUNTIME_UNIT_B64 =
${constant(unit)};

/** SHA-256 of the decoded unit file, asserted by the sync test. */
export const FIRECRACKER_RUNTIME_UNIT_SHA256 =
  "${unitSha}";
`,
);

process.stdout.write(`${path.relative(repoRoot, target)}: ${provisionerSha} ${unitSha}\n`);
