/**
 * Regenerates `convex/provisionerFirecrackerHost.generated.ts` from
 * `deploy/provision-firecracker-host.sh`.
 *
 * The provisioner has to travel inside the rendered install script: `/install --role worker-host`
 * is one curl with nothing else to fetch from this deployment, and Convex bundles TypeScript, not
 * repository files, so the bytes are committed as a generated module rather than read at runtime.
 * Base64, because the provisioner is itself full of heredocs and quotes that no shell-quoting
 * scheme survives verbatim. A test asserts the module matches the script byte for byte, so editing
 * one without rerunning this fails CI instead of shipping a stale provisioner.
 *
 * Usage: pnpm --filter @erainfra/backend embed-firecracker-provisioner
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..", "..", "..");
const source = path.join(repoRoot, "deploy", "provision-firecracker-host.sh");
const target = path.resolve(
  import.meta.dirname,
  "..",
  "convex",
  "provisionerFirecrackerHost.generated.ts",
);

const script = readFileSync(source);
const base64 = script.toString("base64");
const sha256 = createHash("sha256").update(script).digest("hex");

// Newline-joined 76-column lines, because the install script carries this inside a heredoc that
// `base64 -d` reads: wrapped lines diff readably and decode identically.
const lines = base64.match(/.{1,76}/g) ?? [];
writeFileSync(
  target,
  `// GENERATED by scripts/embed-firecracker-provisioner.ts — do not edit.
// Source: deploy/provision-firecracker-host.sh (sha256 ${sha256}).
// Regenerate with: pnpm --filter @erainfra/backend embed-firecracker-provisioner

/** \`deploy/provision-firecracker-host.sh\`, base64-encoded for interpolation into shell. */
export const FIRECRACKER_HOST_PROVISIONER_B64 =
${lines.map((line, index) => `  "${line}${index === lines.length - 1 ? "" : "\\n"}"`).join(" +\n")};

/** SHA-256 of the decoded provisioner, asserted by the sync test. */
export const FIRECRACKER_HOST_PROVISIONER_SHA256 =
  "${sha256}";
`,
);

process.stdout.write(`${path.relative(repoRoot, target)}: ${sha256}\n`);
